#############################################################################
# Makefile for building: GbmuUI.app/Contents/MacOS/GbmuUI
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  GbmuUI/GbmuUI.pro
# Template: app
# Command: /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/qmake -o Makefile GbmuUI/GbmuUI.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -Wall -Wextra -Werror -g -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -IGbmuUI -I. -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang -F/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib
QMAKE         = /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GbmuUI1.0.0
DISTDIR = /Users/nbouchin/Documents/gbmu/.tmp/GbmuUI1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = GbmuUI/main.cpp \
		GbmuUI/gbmuscreen.cpp \
		GbmuUI/mainwindow.cpp \
		GbmuUI/debuggerwindow.cpp \
		GbmuUI/worker.cpp \
		src/Bios.cpp \
		src/Cartridge.cpp \
		src/Debugger.cpp \
		src/Gameboy.cpp \
		src/MemoryBus.cpp \
		src/PPU.class.cpp \
		src/ScreenOutput.class.cpp \
		src/cpu/Core.cpp \
		src/cpu/InputController.cpp \
		src/cpu/InterruptController.cpp \
		src/cpu/Timer.cpp qrc_resource.cpp \
		moc_gbmuscreen.cpp \
		moc_mainwindow.cpp \
		moc_debuggerwindow.cpp \
		moc_worker.cpp
OBJECTS       = main.o \
		gbmuscreen.o \
		mainwindow.o \
		debuggerwindow.o \
		worker.o \
		Bios.o \
		Cartridge.o \
		Debugger.o \
		Gameboy.o \
		MemoryBus.o \
		PPU.class.o \
		ScreenOutput.class.o \
		Core.o \
		InputController.o \
		InterruptController.o \
		Timer.o \
		qrc_resource.o \
		moc_gbmuscreen.o \
		moc_mainwindow.o \
		moc_debuggerwindow.o \
		moc_worker.o
DIST          = /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/qdevice.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/device_config.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/unix.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/mac.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/macx.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/clang.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/qconfig.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		GbmuUI/.qmake.stash \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/default_post.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qml_debug.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/mac.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/resources.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/moc.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/uic.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/yacc.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/lex.prf \
		GbmuUI/GbmuUI/GbmuUI.pro GbmuUI/gbmuscreen.h \
		GbmuUI/mainwindow.h \
		GbmuUI/debuggerwindow.h \
		GbmuUI/worker.h \
		src/AMemoryBankController.hpp \
		src/Bios.hpp \
		src/Cartridge.hpp \
		src/Debugger.hpp \
		src/Fwd.hpp \
		src/Gameboy.hpp \
		src/IReadWrite.hpp \
		src/LCDRegisters.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBankController2.hpp \
		src/MemoryBankController3.hpp \
		src/MemoryBankController5.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/RealTimeClock.hpp \
		src/ScreenOutput.class.h \
		src/UnitWorkingRAM.hpp \
		src/cpu/Core.hpp \
		src/cpu/InputController.hpp \
		src/cpu/InterruptController.hpp \
		src/cpu/Timer.hpp GbmuUI/main.cpp \
		GbmuUI/gbmuscreen.cpp \
		GbmuUI/mainwindow.cpp \
		GbmuUI/debuggerwindow.cpp \
		GbmuUI/worker.cpp \
		src/Bios.cpp \
		src/Cartridge.cpp \
		src/Debugger.cpp \
		src/Gameboy.cpp \
		src/MemoryBus.cpp \
		src/PPU.class.cpp \
		src/ScreenOutput.class.cpp \
		src/cpu/Core.cpp \
		src/cpu/InputController.cpp \
		src/cpu/InterruptController.cpp \
		src/cpu/Timer.cpp
QMAKE_TARGET  = GbmuUI
DESTDIR       = 
TARGET        = GbmuUI.app/Contents/MacOS/GbmuUI

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_debuggerwindow.h $(OBJECTS)  
	@test -d GbmuUI.app/Contents/MacOS/ || mkdir -p GbmuUI.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GbmuUI/GbmuUI.pro /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/qdevice.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/device_config.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/unix.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/mac.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/macx.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/clang.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/qconfig.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/default_post.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qml_debug.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/mac.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/resources.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/moc.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/uic.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/yacc.prf \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/lex.prf \
		GbmuUI/GbmuUI.pro \
		GbmuUI/resource.qrc \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile GbmuUI/GbmuUI.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/spec_pre.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/qdevice.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/device_config.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/unix.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/mac.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/macx.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/sanitize.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/gcc-base.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/clang.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/common/clang-mac.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/qconfig.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt_functions.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt_config.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/sdk.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/toolchain.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/default_pre.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/resolve_config.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/default_post.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/default_post.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qml_debug.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/mac.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/warn_on.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qt.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/resources.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/moc.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/unix/opengl.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/uic.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/unix/thread.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/qmake_use.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/file_copies.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/rez.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/testcase_targets.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/exceptions.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/yacc.prf:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/lex.prf:
GbmuUI/GbmuUI.pro:
GbmuUI/resource.qrc:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl:
/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GbmuUI/GbmuUI.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

GbmuUI.app/Contents/PkgInfo: 
	@test -d GbmuUI.app/Contents || mkdir -p GbmuUI.app/Contents
	@$(DEL_FILE) GbmuUI.app/Contents/PkgInfo
	@echo "APPL????" > GbmuUI.app/Contents/PkgInfo
GbmuUI.app/Contents/Resources/empty.lproj: 
	@test -d GbmuUI.app/Contents/Resources || mkdir -p GbmuUI.app/Contents/Resources
	@touch GbmuUI.app/Contents/Resources/empty.lproj
	
GbmuUI.app/Contents/Info.plist: 
	@test -d GbmuUI.app/Contents || mkdir -p GbmuUI.app/Contents
	@$(DEL_FILE) GbmuUI.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.GbmuUI,g" -e "s,@ICON@,GbmuUI.png,g" -e "s,@EXECUTABLE@,GbmuUI,g" -e "s,@LIBRARY@,GbmuUI,g" -e "s,@TYPEINFO@,????,g" /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang/Info.plist.app >GbmuUI.app/Contents/Info.plist
GbmuUI.app/Contents/Resources/GbmuUI.png: GbmuUI/GbmuUI.png
	@test -d GbmuUI.app/Contents/Resources/ || mkdir -p GbmuUI.app/Contents/Resources/
	@$(DEL_FILE) GbmuUI.app/Contents/Resources/GbmuUI.png
	@$(COPY_FILE) GbmuUI/GbmuUI.png GbmuUI.app/Contents/Resources/GbmuUI.png

all: Makefile \
		GbmuUI.app/Contents/PkgInfo \
		GbmuUI.app/Contents/Resources/empty.lproj \
		GbmuUI.app/Contents/Info.plist \
		GbmuUI.app/Contents/Resources/GbmuUI.png $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents GbmuUI/resource.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents GbmuUI/gbmuscreen.h GbmuUI/mainwindow.h GbmuUI/debuggerwindow.h GbmuUI/worker.h src/AMemoryBankController.hpp src/Bios.hpp src/Cartridge.hpp src/Debugger.hpp src/Fwd.hpp src/Gameboy.hpp src/IReadWrite.hpp src/LCDRegisters.hpp src/MemoryBankController1.hpp src/MemoryBankController2.hpp src/MemoryBankController3.hpp src/MemoryBankController5.hpp src/MemoryBus.hpp src/PPU.class.h src/RealTimeClock.hpp src/ScreenOutput.class.h src/UnitWorkingRAM.hpp src/cpu/Core.hpp src/cpu/InputController.hpp src/cpu/InterruptController.hpp src/cpu/Timer.hpp $(DISTDIR)/
	$(COPY_FILE) --parents GbmuUI/main.cpp GbmuUI/gbmuscreen.cpp GbmuUI/mainwindow.cpp GbmuUI/debuggerwindow.cpp GbmuUI/worker.cpp src/Bios.cpp src/Cartridge.cpp src/Debugger.cpp src/Gameboy.cpp src/MemoryBus.cpp src/PPU.class.cpp src/ScreenOutput.class.cpp src/cpu/Core.cpp src/cpu/InputController.cpp src/cpu/InterruptController.cpp src/cpu/Timer.cpp $(DISTDIR)/
	$(COPY_FILE) --parents GbmuUI/mainwindow.ui GbmuUI/debuggerwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r GbmuUI.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: GbmuUI/resource.qrc \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/rcc \
		GbmuUI/resources/download.png \
		GbmuUI/resources/stop.png \
		GbmuUI/resources/mute.png \
		GbmuUI/resources/play.png \
		GbmuUI/resources/bug.png
	/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/rcc -name resource GbmuUI/resource.qrc -o qrc_resource.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -Wall -Wextra -Werror -g -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_gbmuscreen.cpp moc_mainwindow.cpp moc_debuggerwindow.cpp moc_worker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gbmuscreen.cpp moc_mainwindow.cpp moc_debuggerwindow.cpp moc_worker.cpp
moc_gbmuscreen.cpp: /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QImage \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qimage.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		GbmuUI/gbmuscreen.h \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang -I/Users/nbouchin/Documents/gbmu/GbmuUI -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib GbmuUI/gbmuscreen.h -o moc_gbmuscreen.cpp

moc_mainwindow.cpp: /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		GbmuUI/mainwindow.h \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang -I/Users/nbouchin/Documents/gbmu/GbmuUI -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib GbmuUI/mainwindow.h -o moc_mainwindow.cpp

moc_debuggerwindow.cpp: /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		GbmuUI/debuggerwindow.h \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang -I/Users/nbouchin/Documents/gbmu/GbmuUI -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib GbmuUI/debuggerwindow.h -o moc_debuggerwindow.cpp

moc_worker.cpp: /sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QThread \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QMutex \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		GbmuUI/mainwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		GbmuUI/worker.h \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/mkspecs/macx-clang -I/Users/nbouchin/Documents/gbmu/GbmuUI -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib GbmuUI/worker.h -o moc_worker.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_debuggerwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_debuggerwindow.h
ui_mainwindow.h: GbmuUI/mainwindow.ui \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/uic
	/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/uic GbmuUI/mainwindow.ui -o ui_mainwindow.h

ui_debuggerwindow.h: GbmuUI/debuggerwindow.ui \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/uic
	/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/bin/uic GbmuUI/debuggerwindow.ui -o ui_debuggerwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: GbmuUI/main.cpp GbmuUI/mainwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QToolBar \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QAction \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QIcon \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qicon.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QObject \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o GbmuUI/main.cpp

gbmuscreen.o: GbmuUI/gbmuscreen.cpp GbmuUI/gbmuscreen.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QImage \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qimage.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		GbmuUI/mainwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gbmuscreen.o GbmuUI/gbmuscreen.cpp

mainwindow.o: GbmuUI/mainwindow.cpp GbmuUI/mainwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		ui_mainwindow.h \
		GbmuUI/gbmuscreen.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QImage \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qimage.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		GbmuUI/debuggerwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		GbmuUI/worker.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QThread \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QMutex \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QDesktopServices \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QUrl \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qurl.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o GbmuUI/mainwindow.cpp

debuggerwindow.o: GbmuUI/debuggerwindow.cpp GbmuUI/debuggerwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_debuggerwindow.h \
		GbmuUI/mainwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debuggerwindow.o GbmuUI/debuggerwindow.cpp

worker.o: GbmuUI/worker.cpp GbmuUI/worker.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QThread \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/QMutex \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		GbmuUI/mainwindow.h \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/nbouchin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worker.o GbmuUI/worker.cpp

Bios.o: src/Bios.cpp src/Bios.hpp \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bios.o src/Bios.cpp

Cartridge.o: src/Cartridge.cpp src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/AMemoryBankController.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		src/MemoryBankController2.hpp \
		src/MemoryBankController3.hpp \
		src/RealTimeClock.hpp \
		src/MemoryBankController5.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cartridge.o src/Cartridge.cpp

Debugger.o: src/Debugger.cpp src/Debugger.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/AMemoryBankController.hpp \
		src/MemoryBus.hpp \
		src/Gameboy.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		src/cpu/InterruptController.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debugger.o src/Debugger.cpp

Gameboy.o: src/Gameboy.cpp src/Gameboy.hpp \
		src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		src/Bios.hpp \
		src/LCDRegisters.hpp \
		src/UnitWorkingRAM.hpp \
		src/cpu/InterruptController.hpp \
		src/cpu/InputController.hpp \
		src/cpu/Timer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Gameboy.o src/Gameboy.cpp

MemoryBus.o: src/MemoryBus.cpp src/MemoryBus.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		src/cpu/InterruptController.hpp \
		src/cpu/InputController.hpp \
		src/cpu/Timer.hpp \
		src/LCDRegisters.hpp \
		src/UnitWorkingRAM.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MemoryBus.o src/MemoryBus.cpp

PPU.class.o: src/PPU.class.cpp src/PPU.class.h \
		src/ScreenOutput.class.h \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/cpu/InterruptController.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PPU.class.o src/PPU.class.cpp

ScreenOutput.class.o: src/ScreenOutput.class.cpp src/ScreenOutput.class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScreenOutput.class.o src/ScreenOutput.class.cpp

Core.o: src/cpu/Core.cpp src/cpu/Core.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		utils/Operations_utils.hpp \
		src/Gameboy.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		src/cpu/InterruptController.hpp \
		src/cpu/instructions.inc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Core.o src/cpu/Core.cpp

InputController.o: src/cpu/InputController.cpp src/cpu/InputController.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		src/cpu/InterruptController.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputController.o src/cpu/InputController.cpp

InterruptController.o: src/cpu/InterruptController.cpp src/cpu/InterruptController.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterruptController.o src/cpu/InterruptController.cpp

Timer.o: src/cpu/Timer.cpp src/cpu/Timer.hpp \
		src/Fwd.hpp \
		src/IReadWrite.hpp \
		src/Gameboy.hpp \
		src/cpu/Core.hpp \
		utils/Operations_utils.hpp \
		src/AMemoryBankController.hpp \
		src/Debugger.hpp \
		src/Cartridge.hpp \
		src/MemoryBankController1.hpp \
		src/MemoryBus.hpp \
		src/PPU.class.h \
		src/ScreenOutput.class.h \
		src/cpu/InterruptController.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o src/cpu/Timer.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

moc_gbmuscreen.o: moc_gbmuscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gbmuscreen.o moc_gbmuscreen.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_debuggerwindow.o: moc_debuggerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_debuggerwindow.o moc_debuggerwindow.cpp

moc_worker.o: moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_worker.o moc_worker.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/GbmuUI/bin || mkdir -p $(INSTALL_ROOT)/opt/GbmuUI/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/GbmuUI/bin/GbmuUI.app
	
	-$(QINSTALL) GbmuUI.app $(INSTALL_ROOT)/opt/GbmuUI/bin/GbmuUI.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/GbmuUI/bin/GbmuUI.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/GbmuUI/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

